-- Run this once in the Supabase SQL Editor for the TWD production database.
create table if not exists public.twd_due_date_extension_requests (
    id bigint generated by default as identity primary key,
    issue_id text not null,
    current_due_date date not null,
    requested_due_date date not null,
    reason text not null check (char_length(trim(reason)) > 0),
    requested_by text not null,
    requested_at timestamptz not null default now(),
    status text not null default '待QAV核准' check (status in ('待QAV核准', '核准', '駁回')),
    request_type text not null default '廠商展延申請',
    review_note text,
    reviewed_by text,
    reviewed_at timestamptz
);

create unique index if not exists twd_one_pending_extension_per_issue
    on public.twd_due_date_extension_requests (issue_id)
    where status = '待QAV核准';

alter table public.twd_due_date_extension_requests enable row level security;
revoke all on table public.twd_due_date_extension_requests from anon, authenticated;
grant select, insert, update on table public.twd_due_date_extension_requests to service_role;
grant usage, select on sequence public.twd_due_date_extension_requests_id_seq to service_role;
